In [45]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split


## Task 1: Load and Split the Dataset

Your task: Load the Iris dataset and split it into training and testing sets.


In [52]:
# Load the iris dataset
iris = load_iris()
X, y = iris.data, iris.target

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

## Task 2: Explore the Dataset

Your Task: Print dataset (iris) parameters: feature names, target names, and the shape of the data.<br>
Replace '---' with appropriate code to print feature names, target names, and data shape.


In [53]:
# Print feature names, target names, and data shape
print("Feature names:", iris.feature_names)
print("Target names:", iris.target_names)
print("Training data shape:", X_train.shape)
print("Test data shape:", X_test.shape)


Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']
Training data shape: (105, 4)
Test data shape: (45, 4)


## Task 3: Build and Train the TensorFlow Sequential Model

Your Task: Build a Sequential model with TensorFlow and train it on the Iris dataset.


In [65]:
import tensorflow as tf
import numpy as np

# Convert labels to one-hot encoding
y_train_one_hot = tf.keras.utils.to_categorical(y_train, num_classes=3)
y_test_one_hot = tf.keras.utils.to_categorical(y_test, num_classes=3)

# Initialize the Sequential model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(units=3, activation='softmax', input_shape=(X.shape[1],))
])

# Compile the model
model.compile(optimizer='adam', 
              loss='categorical_crossentropy', 
              metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train_one_hot, epochs=450)


Epoch 1/450
4/4 [==============================] - 0s 2ms/step - loss: 1.6628 - accuracy: 0.3524
Epoch 2/450
4/4 [==============================] - 0s 3ms/step - loss: 1.6376 - accuracy: 0.3429
Epoch 3/450
4/4 [==============================] - 0s 2ms/step - loss: 1.6110 - accuracy: 0.3333
Epoch 4/450
4/4 [==============================] - 0s 2ms/step - loss: 1.5883 - accuracy: 0.3238
Epoch 5/450
4/4 [==============================] - 0s 2ms/step - loss: 1.5646 - accuracy: 0.3143
Epoch 6/450
4/4 [==============================] - 0s 2ms/step - loss: 1.5437 - accuracy: 0.2952
Epoch 7/450
4/4 [==============================] - 0s 2ms/step - loss: 1.5221 - accuracy: 0.2571
Epoch 8/450
4/4 [==============================] - 0s 2ms/step - loss: 1.5013 - accuracy: 0.2095
Epoch 9/450
4/4 [==============================] - 0s 2ms/step - loss: 1.4817 - accuracy: 0.2095
Epoch 10/450
4/4 [==============================] - 0s 2ms/step - loss: 1.4618 - accuracy: 0.1905
Epoch 11/450
4/4 [===========

## Task 4: Evaluate the Model

Your Task: Evaluate the trained model on the test dataset and print the accuracy and confusion matrix.


In [66]:
from sklearn.metrics import accuracy_score, confusion_matrix

# Make predictions on the test set
y_pred_probs = model.predict(X_test)
y_pred = np.argmax(y_pred_probs, axis=1)

# Calculate accuracy and confusion matrix
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)


2/2 [==============================] - 0s 3ms/step
Accuracy: 0.8888888888888888
Confusion Matrix:
 [[19  0  0]
 [ 0  8  5]
 [ 0  0 13]]
